### ISSUE TITLE
Case Matching Question

### ISSUE THREAD

**Issue by CrossR** [lotabout/fuzzy-matcher#1]
Hey!

Love the work here! I've been looking at converting the algorithms here into ReasonML, partially as a learning exercise, and partially since having it as a natively in ReasonML may end up useful for some of my projects in the future.

One oddity I noticed in the Skim code is this:

https://github.com/lotabout/fuzzy-matcher/blob/62d3c86f285fcbde51844853c636d4ce6abbcf12/src/skim.rs#L100-L105

If I'm reading that correctly (and its totally possible I'm not since I don't really know Rust), both `pat_ch` and `ch` are always lower case. This then means the call to `fuzzy_score` is done with lower case characters, even if the character should actually be upper case.

This causes matching to be case insensitive always, so `"a/b/c"` and `"a/B/c"` when matching against `B` both get the same score.

If the `.to_ascii_lowercase()` is removed from the 2 for loops and only applied on line 104 as part of the `if` statement, then the scores are different:

![image](https://user-images.githubusercontent.com/10038688/54159563-2a9ee780-4445-11e9-98c7-d14ca872b4c2.png)

Its possible this is by design, but thought I should check!

**Comment by lotabout** [comment]
@CrossR Glad you like it. I've rechecked the code and you are right here, I'll fix it ASAP.
