### ISSUE TITLE
Question: Does it make sense to reuse matcher?

### ISSUE THREAD

**Issue by Boscop** [lotabout/fuzzy-matcher#10]
Question: Does it make sense to reuse the matcher?
E.g. I'm using it as a custom function registered with sqlite for fuzzy search.
Does it make sense to reuse the same matcher for all queries?
Or is there no benefit from doing that?

---

I.e.
```rust
impl<E> CustomizeConnection<SqliteConnection, E> for ConnectionCustomizer {
	fn on_acquire(&self, conn: &mut SqliteConnection) -> Result<(), E> {
		sql_function!(fn fuzzy_score(text: Text, pattern: Text) -> Nullable<BigInt>);

		fuzzy_score::register_impl(conn, |text: String, pattern: String| {
			let matcher = SkimMatcherV2::default().ignore_case();
			matcher.fuzzy_match(&text, &pattern)
		})
		.unwrap();

		Ok(())
	}
}
```
compared to
```rust
impl<E> CustomizeConnection<SqliteConnection, E> for ConnectionCustomizer {
	fn on_acquire(&self, conn: &mut SqliteConnection) -> Result<(), E> {
		sql_function!(fn fuzzy_score(text: Text, pattern: Text) -> Nullable<BigInt>);

		fuzzy_score::register_impl(conn, |text: String, pattern: String| {
			lazy_static! {
				static ref MATCHER: SkimMatcherV2 = SkimMatcherV2::default().ignore_case();
			}
			MATCHER.fuzzy_match(&text, &pattern)
		})
		.unwrap();

		Ok(())
	}
}
```
Or should it be in an Arc or something? (Btw, this compiles.)

**Comment by lotabout** [comment]
@Boscop Reuse would be better(maybe not a big difference). For

1. `SkimMatcherV2` would reuse the matching buffer allocated in previous run, thus reducing cost for memory allocation. (thread safe by using thread-local)
2.  Allocation for the matcher itself could be avoided to reduce some cost.

Though it make no much difference in normal cases.

**Comment by Boscop** [comment]
@lotabout Thanks! I'm running it in a wasm app where every bit of performance counts..
Does reuse also make sense for the Clangd matcher?

Btw, which one is better / which one would you recommend for doing a fuzzy file search (song library)? :)

**Comment by lotabout** [comment]
@Boscop 
> Does reuse also make sense for the Clangd matcher?

You could assume reuse is always better.

> which one is better / which one would you recommend for doing a fuzzy file search (song library)

It all depends :). But with skim matcher, you could actually tweak the weights for some cases. Might be more flexible.

**Comment by lotabout** [comment]
Feel free to reopen if you have further questions.

**Comment by Boscop** [comment]
@lotabout Thanks. Btw, regarding concurrent access to the matcher, is this safe with sqlite?
Multiple clients can send requests to the server at the same time that cause this function to be called in a query:
```rust
impl<E> CustomizeConnection<SqliteConnection, E> for ConnectionCustomizer {
	fn on_acquire(&self, conn: &mut SqliteConnection) -> Result<(), E> {
		/*lazy_static! {
			static ref MATCHER: impl FuzzyMatcher = new_matcher();
		}*/
		static MATCHER: Lazy<impl FuzzyMatcher> = Lazy::new(|| new_matcher());

		sql_custom_score::register_impl(
			conn,
			|stripped_path: String, p_mandatory: String, p_optional: String| {
				str_custom_score(&*MATCHER, &stripped_path, &p_mandatory, &p_optional)
			},
		)
		.unwrap();

		Ok(())
	}
}
```
